# Generated by Django 3.1.7 on 2021-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acionamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamento',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='acionamento',
            name='telefone',
            field=models.CharField(default=1, help_text='Telefone', max_length=50),
            preserve_default=False,
        ),
    ]
