# Generated by Django 3.1.7 on 2021-03-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acionamentos', '0004_auto_20210307_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acionamento',
            name='user',
        ),
        migrations.AlterField(
            model_name='acionamento',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
