# Generated by Django 3.1.7 on 2021-03-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acionamentos', '0005_auto_20210307_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acionamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
