# Generated by Django 3.1.7 on 2021-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acionamentos', '0007_auto_20210307_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamento',
            name='ativos',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
