# Generated by Django 3.1.7 on 2021-03-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acionamentos', '0010_auto_20210310_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acionamento',
            name='ativos',
            field=models.CharField(choices=[('weqeq', 'weqeq'), ('CENTRAL_1_1_1', 'CENTRAL_1_1_1'), ('CENTRAL_1_1', 'CENTRAL_1_1'), ('TESTE-SONORO-POPUP-VIEW', 'TESTE-SONORO-POPUP-VIEW'), ('DAGSER-PE-EDUDRIVE-STORAGE-REC02_1', 'DAGSER-PE-EDUDRIVE-STORAGE-REC02_1'), ('DAGSER-PE-EDUDRIVE-STORAGE-REC01_1', 'DAGSER-PE-EDUDRIVE-STORAGE-REC01_1'), ('DAGSER-PE-EDUDRIVE-PROXY-REC02_1', 'DAGSER-PE-EDUDRIVE-PROXY-REC02_1'), ('DAGSER-PE-EDUDRIVE-PROXY-REC01_1', 'DAGSER-PE-EDUDRIVE-PROXY-REC01_1'), ('DAGSER-PE-EDUDRIVE-MON-REC01_1_1', 'DAGSER-PE-EDUDRIVE-MON-REC01_1_1'), ('POLLER-DISPLAY_1_3', 'POLLER-DISPLAY_1_3'), ('POLLER-DISPLAY_1_2', 'POLLER-DISPLAY_1_2'), ('POLLER-DISPLAY_1_1', 'POLLER-DISPLAY_1_1'), ('POLLER-DISPLAY_1', 'POLLER-DISPLAY_1'), ('REMOTE-SERVER-TESTE', 'REMOTE-SERVER-TESTE'), ('CENTRAL_1', 'CENTRAL_1'), ('TESTE-NOVO-IC-ADICIONADO', 'TESTE-NOVO-IC-ADICIONADO'), ('teste-RELOAD-remote-server-_NOVO-IC', 'teste-RELOAD-remote-server-_NOVO-IC'), ('Remote-Server-Hml', 'Remote-Server-Hml'), ('HUAWEI_U2000', 'HUAWEI_U2000')], max_length=100),
        ),
    ]
